<?php
declare(strict_types=1);
require __DIR__ . '/../config/config.php';
$catalog=require __DIR__ . '/../data/catalog.php';
$surface='digital';
$pageTitle='REDT Digital | سفارش امن اکانت و اشتراک دیجیتال';
$pageDescription='اکانت، اشتراک و ابزار دیجیتال موردنیازتان را پیدا کنید؛ شرایط تهیه و روش امن فعال‌سازی قبل از اقدام بررسی می‌شود.';
$items=[];
foreach(['accounts'=>'accounts','products'=>'products','courses'=>'courses'] as $group=>$key) foreach(($catalog[$key]??[]) as $item) if($item['active']??true){$item['_group']=$group;$items[]=$item;}
require __DIR__ . '/../includes/surface-header.php';
?>
<main>
<section class="market-hero" id="start"><div class="surface-shell">
    <div class="market-hero__top"><div><span class="section-kicker">فروشگاه خدمات دیجیتال</span><h1>اکانت و اشتراک<br><em>بدون دردسر.</em></h1></div><p>سرویس موردنیازتان را پیدا کنید. قبل از هر اقدامی، شرایط تهیه و روش امن فعال‌سازی را بررسی می‌کنیم و با شما هماهنگ می‌شویم.</p></div>
    <label class="market-search"><span>⌕</span><input type="search" data-digital-search placeholder="مثلاً ChatGPT، Adobe یا طراحی سایت..." aria-label="جستجو در خدمات دیجیتال"><kbd>/</kbd></label>
    <div class="market-shortcuts"><span>جست‌وجوی سریع:</span><button type="button" data-search-term="هوش مصنوعی">هوش مصنوعی</button><button type="button" data-search-term="نرم‌افزار">نرم‌افزار</button><button type="button" data-search-term="طراحی">ابزار طراحی</button><button type="button" data-search-term="آموزش">آموزش</button></div>
    <div class="market-assurance"><span><i>✓</i><b>فعال‌سازی امن</b><small>بدون دریافت رمز حساب</small></span><span><i>✓</i><b>بررسی قبل از اقدام</b><small>هماهنگی کامل با شما</small></span><span><i>✓</i><b>پشتیبانی انسانی</b><small>از درخواست تا تحویل</small></span></div>
</div></section>

<section class="surface-section catalog-section" id="catalog"><div class="surface-shell">
    <div class="catalog-toolbar"><div><span class="section-kicker">انتخاب سرویس</span><h2>دنبال چه چیزی هستید؟</h2></div><div class="catalog-toolbar__aside"><div class="store-filters" role="group" aria-label="فیلتر خدمات"><button class="active" data-digital-filter="all">همه</button><button data-digital-filter="accounts">اکانت‌ها</button><button data-digital-filter="products">ابزارها</button><button data-digital-filter="courses">آموزش</button></div><span class="catalog-result-count" data-digital-count aria-live="polite"><?=fa_number(count($items))?> سرویس قابل بررسی</span></div></div>
    <div class="digital-grid"><?php foreach($items as $item):$label=['accounts'=>'اکانت و اشتراک','products'=>'ابزار دیجیتال','courses'=>'آموزش'][$item['_group']];?><article class="digital-card" data-digital-card data-id="<?=e($item['id'])?>" data-title="<?=e($item['title'])?>" data-price="<?=e($item['price']??'پس از بررسی')?>" data-delivery="<?=e($item['delivery']??'هماهنگی پس از بررسی')?>" data-warranty="<?=e($item['warranty']??'شرایط پس از بررسی')?>" data-group="<?=e($item['_group'])?>" data-search="<?=e($item['title'].' '.$item['category'].' '.$item['desc'].' '.$label)?>">
        <div class="digital-card__visual"><img src="<?=asset_url((string)($item['image']??'assets/images/product-placeholder.svg'))?>" alt="<?=isset($item['image'])?e($item['title']):''?>" width="960" height="720" loading="lazy"></div>
        <div class="digital-card__body"><div class="digital-card__tags"><small><?=e($label)?> · <?=e($item['category'])?></small><span><?=e($item['badge'])?></span></div><h3><?=e($item['title'])?></h3><p><?=e($item['desc'])?></p><strong class="digital-card__price"><?=e($item['price']??'پس از بررسی')?> <small>تومان</small></strong><div class="digital-card__meta"><span><i>↯</i><?=e($item['delivery']??'هماهنگی پس از بررسی')?></span><span><i>◇</i><?=e($item['warranty']??'شرایط پس از بررسی')?></span></div><label class="digital-compare"><input type="checkbox" data-compare-product><span>افزودن به مقایسه</span></label><button type="button" data-digital-order data-id="<?=e($item['id'])?>" data-title="<?=e($item['title'])?>" data-kind="<?=e($label)?>"><span>بررسی و ثبت درخواست</span><i>↙</i></button></div>
    </article><?php endforeach;?></div>
    <div class="digital-empty" hidden><b>نتیجه‌ای پیدا نشد</b><span>نام سرویس را برای ما بنویسید تا بررسی کنیم.</span><a href="#support">ثبت درخواست اختصاصی</a></div>
    <section class="digital-compare-panel" data-compare-panel hidden aria-live="polite"><header><div><span>مقایسه محصولات</span><b data-compare-summary>محصولی انتخاب نشده است</b></div><button type="button" data-compare-clear>پاک‌کردن انتخاب‌ها</button></header><div class="digital-compare-table" data-compare-table></div></section>
</div></section>

<section class="surface-section digital-process" id="how"><div class="surface-shell"><div class="section-head"><div><span class="section-kicker">روش سفارش</span><h2>سه قدم ساده<br><em>تا فعال‌سازی.</em></h2></div><p>ثبت درخواست به‌معنی پرداخت نیست. اول جزئیات را بررسی می‌کنیم و فقط پس از تأیید شما ادامه می‌دهیم.</p></div><div class="process-cards"><article><span>01</span><i>⌕</i><h3>سرویس را انتخاب کنید</h3><p>نام اکانت یا ابزار موردنیازتان را جست‌وجو کنید.</p></article><article><span>02</span><i>◎</i><h3>شرایط را بررسی می‌کنیم</h3><p>موجودی و روش امن فعال‌سازی برای شما مشخص می‌شود.</p></article><article><span>03</span><i>✓</i><h3>بعد از تأیید شما</h3><p>سفارش انجام می‌شود و تا تحویل همراهتان هستیم.</p></article></div></div></section>

<section class="surface-section digital-tracking" id="tracking"><div class="surface-shell lead-wrap"><div class="lead-copy"><span class="section-kicker">ORDER TRACKING</span><h2>سفارش کجاست؟</h2><p>کد پیگیری و شماره موبایلی که هنگام سفارش ثبت کرده‌اید وارد کنید. جزئیات شخصی نمایش داده نمی‌شود.</p></div><form class="lead-form" action="<?=url('api/track-order.php')?>" method="post" data-order-tracking><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><label>کد پیگیری<input name="tracking_code" required dir="ltr" autocomplete="off" placeholder="RDT-XXXXXXXXXX"></label><label>شماره موبایل<input name="phone" required inputmode="numeric" dir="ltr" autocomplete="tel" placeholder="0912 000 0000"></label><small class="form-message" role="status" aria-live="polite"></small><button type="submit">پیگیری سفارش <i>↙</i></button></form></div></section>

<section class="surface-section lead-section digital-support" id="support"><div class="surface-shell lead-wrap"><div class="lead-copy"><span class="section-kicker">CAN'T FIND IT?</span><h2>هر سرویسی که<br><em>اینجا نیست.</em></h2><p>نام ابزار یا اشتراک را بنویسید؛ امکان تهیه و روش امن فعال‌سازی آن را بررسی می‌کنیم.</p><div class="lead-promise"><span>یادآوری امنیتی</span><b>رمز حسابتان را نمی‌خواهیم</b></div></div><form class="lead-form" action="<?=url('api/order.php')?>" method="post" data-lead-form><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="budget" value="نیازمند گفتگو"><input type="hidden" name="service" value="درخواست سرویس دیجیتال"><input class="hp" name="website" tabindex="-1" autocomplete="off"><label>نام سرویس و توضیح درخواست<textarea name="message" rows="4" minlength="10" required placeholder="مثلاً اشتراک یک‌ساله ابزار مورد نظر روی ایمیل شخصی..."></textarea></label><div class="lead-form__row"><label>نام و نام خانوادگی<input name="name" required minlength="3" autocomplete="name" placeholder="نام شما"></label><label>شماره موبایل<input name="phone" required inputmode="tel" dir="ltr" autocomplete="tel" placeholder="0912 000 0000"></label></div><small class="form-message" role="alert"></small><button type="submit">بررسی این سرویس <i>↙</i></button><small class="lead-privacy">هیچ‌وقت رمز حساب یا اطلاعات بانکی را در فرم وارد نکنید.</small></form></div></section>
</main>

<div class="order-sheet" hidden role="dialog" aria-modal="true" aria-labelledby="digital-order-title"><button class="order-sheet__backdrop" data-sheet-close aria-label="بستن"></button><section class="order-sheet__panel"><div class="sheet-handle"></div><button class="sheet-close" data-sheet-close aria-label="بستن">×</button><span class="section-kicker">SECURE REQUEST</span><h2 id="digital-order-title">ثبت درخواست سرویس</h2><p>جزئیات سرویس بررسی می‌شود و پیش از هر اقدامی با شما هماهنگ می‌کنیم.</p><form action="<?=url('api/purchase.php')?>" method="post" data-digital-purchase><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="product_id"><input type="hidden" name="plan"><input class="hp" name="website" tabindex="-1" autocomplete="off"><div class="order-summary"><span data-order-kind>خدمات دیجیتال</span><b data-order-title>سرویس انتخاب‌شده</b><small>بررسی موجودی و شرایط فعال‌سازی</small></div><div class="lead-form__row"><label>نام و نام خانوادگی<input name="name" required minlength="3" autocomplete="name" placeholder="نام شما"></label><label>شماره موبایل<input name="phone" required inputmode="tel" dir="ltr" autocomplete="tel" placeholder="0912 000 0000"></label></div><label>ایمیل حساب <small>اختیاری؛ رمز عبور را وارد نکنید.</small><input name="account" type="email" dir="ltr" autocomplete="email" placeholder="name@example.com"></label><label>توضیحات<textarea name="notes" rows="3" placeholder="نوع پلن یا زمان مورد نظر..."></textarea></label><small class="form-message" role="alert"></small><button type="submit">ثبت امن درخواست <i>↙</i></button><small class="lead-privacy">ثبت درخواست به‌معنی پرداخت یا تعهد نیست.</small></form><div class="sheet-success" hidden><b>✓</b><h3>درخواست ثبت شد.</h3><p>کد پیگیری: <strong data-sheet-code></strong></p><span>پس از واریز، فیش و مدارک تطبیق پرداخت را امن ارسال کنید.</span><a class="sheet-verify" data-sheet-verify href="#">ادامه احراز هویت و ارسال فیش ←</a><button type="button" data-sheet-close>بعداً انجام می‌دهم</button></div></section></div>
<?php require __DIR__ . '/../includes/surface-footer.php'; ?>
