CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY, full_name TEXT NOT NULL, phone TEXT NOT NULL UNIQUE, email TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, tracking_code TEXT NOT NULL UNIQUE, customer_id TEXT NOT NULL REFERENCES customers(id), source TEXT NOT NULL DEFAULT 'purchase', product_id TEXT, product_title TEXT NOT NULL, group_name TEXT, plan TEXT, price_snapshot TEXT, activation_email TEXT, notes TEXT, status TEXT NOT NULL DEFAULT 'awaiting_payment', payment_status TEXT NOT NULL DEFAULT 'not_submitted', identity_status TEXT NOT NULL DEFAULT 'not_submitted', verification_token_hash TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS verifications (id TEXT PRIMARY KEY, order_id TEXT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE, provider TEXT NOT NULL, receipt_location TEXT NOT NULL, receipt_mime TEXT NOT NULL, bank_card_location TEXT NOT NULL, bank_card_mime TEXT NOT NULL, national_card_location TEXT NOT NULL, national_card_mime TEXT NOT NULL, national_id_ciphertext TEXT NOT NULL, card_last4 TEXT NOT NULL, consent_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', reviewer_note TEXT, reviewed_at TEXT, delete_after TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_events (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, event_type TEXT NOT NULL, previous_status TEXT, new_status TEXT, actor TEXT NOT NULL, metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS leads (id TEXT PRIMARY KEY, full_name TEXT NOT NULL, phone TEXT NOT NULL, service TEXT, budget TEXT, message TEXT, status TEXT NOT NULL DEFAULT 'new', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS product_overrides (group_name TEXT NOT NULL, product_id TEXT NOT NULL, active INTEGER NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(group_name, product_id));
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_verifications_status ON verifications(status, created_at DESC);
