<?php
declare(strict_types=1);
require __DIR__.'/../config/config.php';
if(!is_post()) json_response(['ok'=>false,'message'=>'درخواست نامعتبر است.'],405);
if(!csrf_valid($_POST['csrf']??null)) json_response(['ok'=>false,'message'=>'نشست منقضی شده؛ صفحه را تازه کنید.'],419);
if(!empty($_POST['website'])) json_response(['ok'=>true,'message'=>'درخواست شما ثبت شد.']);
$last=(int)($_SESSION['last_submit']??0); if(time()-$last<20) json_response(['ok'=>false,'message'=>'لطفاً کمی بعد دوباره تلاش کنید.'],429);
$normalizeDigits=static fn(string $value):string=>strtr($value,['۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']);
$name=trim((string)($_POST['name']??''));
$phone=preg_replace('/[^0-9+]/','',$normalizeDigits((string)($_POST['phone']??'')));
$service=trim((string)($_POST['service']??''));
$message=trim((string)($_POST['message']??''));
$timeline=trim((string)($_POST['timeline']??''));
$budget=trim((string)($_POST['budget']??''));
$contactMethod=trim((string)($_POST['contact_method']??'تماس تلفنی'));
$allowedServices=['سایت و تجربه دیجیتال','تبلیغات و کمپین','ویدیو و محتوا','خدمات دیجیتال','هنوز مطمئن نیستم'];
$allowedContactMethods=['تماس تلفنی','پیامک','واتساپ'];
$errors=[];
if(mb_strlen($name)<3)$errors['name']='نام کامل را وارد کنید.';
if(!preg_match('/^(?:\+98|0)?9\d{9}$/',(string)$phone))$errors['phone']='شماره موبایل معتبر نیست.';
if(!in_array($service,$allowedServices,true))$errors['service']='یک موضوع معتبر انتخاب کنید.';
if(mb_strlen($message)<10)$errors['message']='کمی بیشتر درباره هدف یا مشکل بنویسید.';
if(!in_array($contactMethod,$allowedContactMethods,true))$errors['contact_method']='روش ارتباط معتبر نیست.';
if($errors)json_response(['ok'=>false,'message'=>'لطفاً خطاهای فرم را اصلاح کنید.','errors'=>$errors],422);
if(!is_dir(STORAGE_PATH.'/messages'))mkdir(STORAGE_PATH.'/messages',0755,true);
$record=json_encode(['date'=>date(DATE_ATOM),'name'=>$name,'phone'=>$phone,'service'=>$service,'message'=>$message,'timeline'=>$timeline,'budget'=>$budget,'contact_method'=>$contactMethod],JSON_UNESCAPED_UNICODE).PHP_EOL;
file_put_contents(STORAGE_PATH.'/messages/consultations.log',$record,FILE_APPEND|LOCK_EX);
$_SESSION['last_submit']=time();
json_response(['ok'=>true,'message'=>'درخواست شما ثبت شد. حداکثر تا یک روز کاری برای هماهنگی تماس می‌گیریم.']);
